// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.2.2
// LVGL version: 8.2.0
// Project name: qems

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////
lv_obj_t * ui_Screen_Loading;
lv_obj_t * ui_S1P_Border;
lv_obj_t * ui_S1SP_Loading;
lv_obj_t * ui_S1L_Name;
lv_obj_t * ui_S1L_Info;
lv_obj_t * ui_S1I_CO2;
lv_obj_t * ui_Screen_Data;
lv_obj_t * ui_S2P_Header;
lv_obj_t * ui_S2I_Icon;
lv_obj_t * ui_S2L_Header;
lv_obj_t * ui_S2P_Content;
lv_obj_t * ui_S2L_Time;
lv_obj_t * ui_S2L_Date;
lv_obj_t * ui_S2L_Cost_Save;
lv_obj_t * ui_S2L_CO2_Save;
lv_obj_t * ui_S2L_Load;
lv_obj_t * ui_S2I_CO2_Save;
lv_obj_t * ui_S2I_Cost_Save;
lv_obj_t * ui_Screen_Settings;
lv_obj_t * ui_S3P_Border;
lv_obj_t * ui_S3L_IP_Name;
lv_obj_t * ui_S3L_IP_Data;
lv_obj_t * ui_S3L_WiFi_Name;
lv_obj_t * ui_S3L_WiFi_Data;
lv_obj_t * ui_S3B_Back;
lv_obj_t * ui_S3L_Back;
lv_obj_t * ui_S3B_Reboot;
lv_obj_t * ui_S3L_Reboot;
lv_obj_t * ui_S3B_WiFi_Reset;
lv_obj_t * ui_S3L_WiFi_Reset;
lv_obj_t * ui_S3B_Factory_Reset;
lv_obj_t * ui_S3L_Back1;
lv_obj_t * ui_S3P_Header;
lv_obj_t * ui_S3I_Icon;
lv_obj_t * ui_S3L_Header;
lv_obj_t * ui_Screen_WiFi;
lv_obj_t * ui_S4P_Border;
lv_obj_t * ui_S4L_Info;
lv_obj_t * ui_S4L_Info2;
lv_obj_t * ui_S4L_Info1;
lv_obj_t * ui_S4P_Header;
lv_obj_t * ui_S4I_Icon;
lv_obj_t * ui_S4L_Header;
lv_obj_t * ui_S4SP_Spinner;
lv_obj_t * ui_Screen_Upload;
lv_obj_t * ui_S5P_Border;
lv_obj_t * ui_S5L_Info_1;
lv_obj_t * ui_S4L_Info4;
lv_obj_t * ui_S5L_IP;
lv_obj_t * ui_S5P_Header;
lv_obj_t * ui_S5I_Icon;
lv_obj_t * ui_S5L_Header;
lv_obj_t * ui_S5SP_Spinner;
lv_obj_t * ui____initial_actions0;

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////

///////////////////// SCREENS ////////////////////
void ui_Screen_Loading_screen_init(void)
{
    ui_Screen_Loading = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen_Loading, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_S1P_Border = lv_obj_create(ui_Screen_Loading);
    lv_obj_set_width(ui_S1P_Border, 310);
    lv_obj_set_height(ui_S1P_Border, 230);
    lv_obj_set_align(ui_S1P_Border, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_S1P_Border, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_S1P_Border, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_S1P_Border, lv_color_hex(0x2B2B2B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_S1P_Border, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_S1P_Border, lv_color_hex(0x00A39B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_S1P_Border, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_S1SP_Loading = lv_spinner_create(ui_S1P_Border, 1000, 90);
    lv_obj_set_width(ui_S1SP_Loading, 90);
    lv_obj_set_height(ui_S1SP_Loading, 90);
    lv_obj_set_align(ui_S1SP_Loading, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_S1SP_Loading, LV_OBJ_FLAG_CLICKABLE);      /// Flags

    lv_obj_set_style_arc_color(ui_S1SP_Loading, lv_color_hex(0x00A39B), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_S1SP_Loading, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_S1L_Name = lv_label_create(ui_S1P_Border);
    lv_obj_set_width(ui_S1L_Name, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_S1L_Name, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_S1L_Name, 0);
    lv_obj_set_y(ui_S1L_Name, -80);
    lv_obj_set_align(ui_S1L_Name, LV_ALIGN_CENTER);
    lv_label_set_text(ui_S1L_Name, "QEMS Demo");
    lv_obj_set_style_text_color(ui_S1L_Name, lv_color_hex(0x00A39B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_S1L_Name, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_S1L_Name, &ui_font_Raleway24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_S1L_Info = lv_label_create(ui_S1P_Border);
    lv_obj_set_width(ui_S1L_Info, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_S1L_Info, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_S1L_Info, 0);
    lv_obj_set_y(ui_S1L_Info, 80);
    lv_obj_set_align(ui_S1L_Info, LV_ALIGN_CENTER);
    lv_label_set_text(ui_S1L_Info, "Verbindung zum WiFI Netzwerk wird\nhergestellt...");
    lv_obj_set_style_text_color(ui_S1L_Info, lv_color_hex(0x00A39B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_S1L_Info, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_S1L_Info, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_S1L_Info, &ui_font_Raleway16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_S1I_CO2 = lv_img_create(ui_S1P_Border);
    lv_img_set_src(ui_S1I_CO2, &ui_img_leaf_green_png);
    lv_obj_set_width(ui_S1I_CO2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_S1I_CO2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_S1I_CO2, 1);
    lv_obj_set_y(ui_S1I_CO2, 2);
    lv_obj_set_align(ui_S1I_CO2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_S1I_CO2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_S1I_CO2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

}
void ui_Screen_Data_screen_init(void)
{
    ui_Screen_Data = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen_Data, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_S2P_Header = lv_obj_create(ui_Screen_Data);
    lv_obj_set_width(ui_S2P_Header, 310);
    lv_obj_set_height(ui_S2P_Header, 50);
    lv_obj_set_x(ui_S2P_Header, 0);
    lv_obj_set_y(ui_S2P_Header, -115);
    lv_obj_set_align(ui_S2P_Header, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_S2P_Header, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_S2P_Header, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_S2P_Header, lv_color_hex(0x202020), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_S2P_Header, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_S2P_Header, lv_color_hex(0x00A39B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_S2P_Header, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_S2P_Header, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_S2P_Header, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_S2P_Header, lv_color_hex(0x0097FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_S2P_Header, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_S2P_Header, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_S2I_Icon = lv_img_create(ui_S2P_Header);
    lv_img_set_src(ui_S2I_Icon, &ui_img_leaf_white_png);
    lv_obj_set_width(ui_S2I_Icon, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_S2I_Icon, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_S2I_Icon, -136);
    lv_obj_set_y(ui_S2I_Icon, 10);
    lv_obj_set_align(ui_S2I_Icon, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_S2I_Icon, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_S2I_Icon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_S2I_Icon, 192);

    ui_S2L_Header = lv_label_create(ui_S2P_Header);
    lv_obj_set_width(ui_S2L_Header, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_S2L_Header, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_S2L_Header, 30);
    lv_obj_set_y(ui_S2L_Header, 11);
    lv_obj_set_align(ui_S2L_Header, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_S2L_Header, "Quartierenergiebilanz");
    lv_obj_set_style_text_font(ui_S2L_Header, &ui_font_Raleway18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_S2P_Content = lv_obj_create(ui_Screen_Data);
    lv_obj_set_width(ui_S2P_Content, 310);
    lv_obj_set_height(ui_S2P_Content, 200);
    lv_obj_set_x(ui_S2P_Content, 0);
    lv_obj_set_y(ui_S2P_Content, 15);
    lv_obj_set_align(ui_S2P_Content, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_S2P_Content, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_S2P_Content, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_S2P_Content, lv_color_hex(0x2B2B2B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_S2P_Content, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_S2P_Content, lv_color_hex(0x00A39B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_S2P_Content, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_S2L_Time = lv_label_create(ui_S2P_Content);
    lv_obj_set_width(ui_S2L_Time, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_S2L_Time, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_S2L_Time, 5);
    lv_obj_set_y(ui_S2L_Time, -55);
    lv_obj_set_align(ui_S2L_Time, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_S2L_Time, "12:00:00");
    lv_obj_set_style_text_font(ui_S2L_Time, &ui_font_MonoFonto18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_S2L_Date = lv_label_create(ui_S2P_Content);
    lv_obj_set_width(ui_S2L_Date, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_S2L_Date, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_S2L_Date, 5);
    lv_obj_set_y(ui_S2L_Date, -80);
    lv_obj_set_align(ui_S2L_Date, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_S2L_Date, "00.00.0000");
    lv_obj_set_style_text_font(ui_S2L_Date, &ui_font_MonoFonto18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_S2L_Cost_Save = lv_label_create(ui_S2P_Content);
    lv_obj_set_width(ui_S2L_Cost_Save, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_S2L_Cost_Save, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_S2L_Cost_Save, -40);
    lv_obj_set_y(ui_S2L_Cost_Save, 65);
    lv_obj_set_align(ui_S2L_Cost_Save, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_S2L_Cost_Save, "0%");
    lv_obj_set_style_text_font(ui_S2L_Cost_Save, &ui_font_Raleway24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_S2L_CO2_Save = lv_label_create(ui_S2P_Content);
    lv_obj_set_width(ui_S2L_CO2_Save, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_S2L_CO2_Save, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_S2L_CO2_Save, -5);
    lv_obj_set_y(ui_S2L_CO2_Save, 12);
    lv_obj_set_align(ui_S2L_CO2_Save, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_S2L_CO2_Save, "0%");
    lv_obj_set_style_text_font(ui_S2L_CO2_Save, &ui_font_Raleway24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_S2L_Load = lv_label_create(ui_S2P_Content);
    lv_obj_set_width(ui_S2L_Load, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_S2L_Load, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_S2L_Load, 199);
    lv_obj_set_y(ui_S2L_Load, 51);
    lv_label_set_text(ui_S2L_Load, "Lade Daten...");
    lv_obj_add_flag(ui_S2L_Load, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_text_color(ui_S2L_Load, lv_color_hex(0x00A39B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_S2L_Load, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_S2L_Load, &ui_font_Raleway16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_S2I_CO2_Save = lv_img_create(ui_Screen_Data);
    lv_img_set_src(ui_S2I_CO2_Save, &ui_img_co2_save_png);
    lv_obj_set_width(ui_S2I_CO2_Save, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_S2I_CO2_Save, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_S2I_CO2_Save, 59);
    lv_obj_set_y(ui_S2I_CO2_Save, 28);
    lv_obj_set_align(ui_S2I_CO2_Save, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_S2I_CO2_Save, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_S2I_CO2_Save, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_S2I_Cost_Save = lv_img_create(ui_Screen_Data);
    lv_img_set_src(ui_S2I_Cost_Save, &ui_img_cost_save_png);
    lv_obj_set_width(ui_S2I_Cost_Save, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_S2I_Cost_Save, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_S2I_Cost_Save, 24);
    lv_obj_set_y(ui_S2I_Cost_Save, 80);
    lv_obj_set_align(ui_S2I_Cost_Save, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_S2I_Cost_Save, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_S2I_Cost_Save, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

}
void ui_Screen_Settings_screen_init(void)
{
    ui_Screen_Settings = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen_Settings, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_S3P_Border = lv_obj_create(ui_Screen_Settings);
    lv_obj_set_width(ui_S3P_Border, 310);
    lv_obj_set_height(ui_S3P_Border, 200);
    lv_obj_set_x(ui_S3P_Border, 1);
    lv_obj_set_y(ui_S3P_Border, 15);
    lv_obj_set_align(ui_S3P_Border, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_S3P_Border, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_S3P_Border, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_S3P_Border, lv_color_hex(0x2B2B2B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_S3P_Border, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_S3P_Border, lv_color_hex(0x00A39B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_S3P_Border, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_S3L_IP_Name = lv_label_create(ui_S3P_Border);
    lv_obj_set_width(ui_S3L_IP_Name, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_S3L_IP_Name, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_S3L_IP_Name, -7);
    lv_obj_set_y(ui_S3L_IP_Name, -3);
    lv_label_set_text(ui_S3L_IP_Name, "IP Address:");
    lv_obj_set_style_text_color(ui_S3L_IP_Name, lv_color_hex(0x00A39B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_S3L_IP_Name, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_S3L_IP_Name, &ui_font_Raleway16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_S3L_IP_Data = lv_label_create(ui_S3P_Border);
    lv_obj_set_width(ui_S3L_IP_Data, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_S3L_IP_Data, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_S3L_IP_Data, 80);
    lv_obj_set_y(ui_S3L_IP_Data, -2);
    lv_label_set_text(ui_S3L_IP_Data, "192.168.0.1");
    lv_obj_set_style_text_color(ui_S3L_IP_Data, lv_color_hex(0x00A39B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_S3L_IP_Data, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_S3L_IP_Data, &ui_font_Raleway16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_S3L_WiFi_Name = lv_label_create(ui_S3P_Border);
    lv_obj_set_width(ui_S3L_WiFi_Name, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_S3L_WiFi_Name, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_S3L_WiFi_Name, -6);
    lv_obj_set_y(ui_S3L_WiFi_Name, 20);
    lv_label_set_text(ui_S3L_WiFi_Name, "WiFi Name:");
    lv_obj_set_style_text_color(ui_S3L_WiFi_Name, lv_color_hex(0x00A39B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_S3L_WiFi_Name, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_S3L_WiFi_Name, &ui_font_Raleway16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_S3L_WiFi_Data = lv_label_create(ui_S3P_Border);
    lv_obj_set_width(ui_S3L_WiFi_Data, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_S3L_WiFi_Data, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_S3L_WiFi_Data, 80);
    lv_obj_set_y(ui_S3L_WiFi_Data, 20);
    lv_label_set_text(ui_S3L_WiFi_Data, "WiFi Name");
    lv_obj_set_style_text_color(ui_S3L_WiFi_Data, lv_color_hex(0x00A39B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_S3L_WiFi_Data, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_S3L_WiFi_Data, &ui_font_Raleway16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_S3B_Back = lv_btn_create(ui_S3P_Border);
    lv_obj_set_width(ui_S3B_Back, 100);
    lv_obj_set_height(ui_S3B_Back, 36);
    lv_obj_set_x(ui_S3B_Back, 100);
    lv_obj_set_y(ui_S3B_Back, 75);
    lv_obj_set_align(ui_S3B_Back, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_S3B_Back, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_S3B_Back, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_S3B_Back, lv_color_hex(0x00A39B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_S3B_Back, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_S3B_Back, lv_color_hex(0x2B2B2B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_S3B_Back, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_S3B_Back, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_S3B_Back, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_S3L_Back = lv_label_create(ui_S3B_Back);
    lv_obj_set_width(ui_S3L_Back, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_S3L_Back, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_S3L_Back, LV_ALIGN_CENTER);
    lv_label_set_text(ui_S3L_Back, "Zurueck");
    lv_obj_set_style_text_font(ui_S3L_Back, &ui_font_Raleway16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_S3B_Reboot = lv_btn_create(ui_S3P_Border);
    lv_obj_set_width(ui_S3B_Reboot, 100);
    lv_obj_set_height(ui_S3B_Reboot, 36);
    lv_obj_set_x(ui_S3B_Reboot, 100);
    lv_obj_set_y(ui_S3B_Reboot, -25);
    lv_obj_set_align(ui_S3B_Reboot, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_S3B_Reboot, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_S3B_Reboot, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_S3B_Reboot, lv_color_hex(0x00A39B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_S3B_Reboot, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_S3B_Reboot, lv_color_hex(0x2B2B2B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_S3B_Reboot, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_S3B_Reboot, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_S3B_Reboot, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_S3L_Reboot = lv_label_create(ui_S3B_Reboot);
    lv_obj_set_width(ui_S3L_Reboot, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_S3L_Reboot, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_S3L_Reboot, LV_ALIGN_CENTER);
    lv_label_set_text(ui_S3L_Reboot, "Neustart");
    lv_obj_set_style_text_font(ui_S3L_Reboot, &ui_font_Raleway16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_S3B_WiFi_Reset = lv_btn_create(ui_S3P_Border);
    lv_obj_set_width(ui_S3B_WiFi_Reset, 100);
    lv_obj_set_height(ui_S3B_WiFi_Reset, 36);
    lv_obj_set_x(ui_S3B_WiFi_Reset, 100);
    lv_obj_set_y(ui_S3B_WiFi_Reset, -70);
    lv_obj_set_align(ui_S3B_WiFi_Reset, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_S3B_WiFi_Reset, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_S3B_WiFi_Reset, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_S3B_WiFi_Reset, lv_color_hex(0x00A39B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_S3B_WiFi_Reset, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_S3B_WiFi_Reset, lv_color_hex(0x2B2B2B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_S3B_WiFi_Reset, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_S3B_WiFi_Reset, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_S3B_WiFi_Reset, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_S3L_WiFi_Reset = lv_label_create(ui_S3B_WiFi_Reset);
    lv_obj_set_width(ui_S3L_WiFi_Reset, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_S3L_WiFi_Reset, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_S3L_WiFi_Reset, LV_ALIGN_CENTER);
    lv_label_set_text(ui_S3L_WiFi_Reset, "Reset");
    lv_obj_set_style_text_font(ui_S3L_WiFi_Reset, &ui_font_Raleway16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_S3B_Factory_Reset = lv_btn_create(ui_S3P_Border);
    lv_obj_set_width(ui_S3B_Factory_Reset, 136);
    lv_obj_set_height(ui_S3B_Factory_Reset, 36);
    lv_obj_set_x(ui_S3B_Factory_Reset, -10);
    lv_obj_set_y(ui_S3B_Factory_Reset, 75);
    lv_obj_set_align(ui_S3B_Factory_Reset, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_S3B_Factory_Reset, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_S3B_Factory_Reset, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_S3B_Factory_Reset, lv_color_hex(0x801F1F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_S3B_Factory_Reset, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_S3B_Factory_Reset, lv_color_hex(0xD16565), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_S3B_Factory_Reset, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_S3B_Factory_Reset, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_S3B_Factory_Reset, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_S3L_Back1 = lv_label_create(ui_S3B_Factory_Reset);
    lv_obj_set_width(ui_S3L_Back1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_S3L_Back1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_S3L_Back1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_S3L_Back1, "Werkseinstellung");
    lv_obj_set_style_text_font(ui_S3L_Back1, &ui_font_Raleway16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_S3P_Header = lv_obj_create(ui_Screen_Settings);
    lv_obj_set_width(ui_S3P_Header, 310);
    lv_obj_set_height(ui_S3P_Header, 50);
    lv_obj_set_x(ui_S3P_Header, 0);
    lv_obj_set_y(ui_S3P_Header, -115);
    lv_obj_set_align(ui_S3P_Header, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_S3P_Header, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_S3P_Header, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_S3P_Header, lv_color_hex(0x202020), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_S3P_Header, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_S3P_Header, lv_color_hex(0x00A39B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_S3P_Header, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_S3P_Header, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_S3P_Header, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_S3P_Header, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_S3I_Icon = lv_img_create(ui_S3P_Header);
    lv_img_set_src(ui_S3I_Icon, &ui_img_gears_white_png);
    lv_obj_set_width(ui_S3I_Icon, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_S3I_Icon, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_S3I_Icon, -136);
    lv_obj_set_y(ui_S3I_Icon, 10);
    lv_obj_set_align(ui_S3I_Icon, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_S3I_Icon, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_S3I_Icon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_S3I_Icon, 192);

    ui_S3L_Header = lv_label_create(ui_S3P_Header);
    lv_obj_set_width(ui_S3L_Header, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_S3L_Header, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_S3L_Header, 30);
    lv_obj_set_y(ui_S3L_Header, 11);
    lv_obj_set_align(ui_S3L_Header, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_S3L_Header, "Einstellungen");
    lv_obj_set_style_text_font(ui_S3L_Header, &ui_font_Raleway18, LV_PART_MAIN | LV_STATE_DEFAULT);

}
void ui_Screen_WiFi_screen_init(void)
{
    ui_Screen_WiFi = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen_WiFi, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_S4P_Border = lv_obj_create(ui_Screen_WiFi);
    lv_obj_set_width(ui_S4P_Border, 310);
    lv_obj_set_height(ui_S4P_Border, 200);
    lv_obj_set_x(ui_S4P_Border, 1);
    lv_obj_set_y(ui_S4P_Border, 15);
    lv_obj_set_align(ui_S4P_Border, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_S4P_Border, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_S4P_Border, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_S4P_Border, lv_color_hex(0x2B2B2B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_S4P_Border, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_S4P_Border, lv_color_hex(0x00A39B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_S4P_Border, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_S4L_Info = lv_label_create(ui_S4P_Border);
    lv_obj_set_width(ui_S4L_Info, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_S4L_Info, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_S4L_Info, 0);
    lv_obj_set_y(ui_S4L_Info, -2);
    lv_obj_set_align(ui_S4L_Info, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_S4L_Info,
                      "Es konnte kein Zugang zu einem WiFi\nNetzwerk hergestellt werden. Bitte\nverbinden Sie sich mit dem Access Point");
    lv_obj_set_style_text_color(ui_S4L_Info, lv_color_hex(0x00A39B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_S4L_Info, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_S4L_Info, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_S4L_Info, &ui_font_Raleway16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_S4L_Info2 = lv_label_create(ui_S4P_Border);
    lv_obj_set_width(ui_S4L_Info2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_S4L_Info2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_S4L_Info2, 0);
    lv_obj_set_y(ui_S4L_Info2, 80);
    lv_obj_set_align(ui_S4L_Info2, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_S4L_Info2,
                      "und oeffnen Sie die IP Adresse\n192.168.4.1\nin Ihrem Browser um ein Netzwerk zu\nkonfigurieren.");
    lv_obj_set_style_text_color(ui_S4L_Info2, lv_color_hex(0x00A39B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_S4L_Info2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_S4L_Info2, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_S4L_Info2, &ui_font_Raleway16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_S4L_Info1 = lv_label_create(ui_S4P_Border);
    lv_obj_set_width(ui_S4L_Info1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_S4L_Info1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_S4L_Info1, 0);
    lv_obj_set_y(ui_S4L_Info1, -20);
    lv_obj_set_align(ui_S4L_Info1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_S4L_Info1, "QEMS Demo");
    lv_obj_set_style_text_color(ui_S4L_Info1, lv_color_hex(0x00A39B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_S4L_Info1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_S4L_Info1, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_S4L_Info1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_S4L_Info1, &ui_font_Raleway24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_S4P_Header = lv_obj_create(ui_Screen_WiFi);
    lv_obj_set_width(ui_S4P_Header, 310);
    lv_obj_set_height(ui_S4P_Header, 50);
    lv_obj_set_x(ui_S4P_Header, 0);
    lv_obj_set_y(ui_S4P_Header, -115);
    lv_obj_set_align(ui_S4P_Header, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_S4P_Header, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_S4P_Header, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_S4P_Header, lv_color_hex(0x202020), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_S4P_Header, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_S4P_Header, lv_color_hex(0x00A39B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_S4P_Header, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_S4P_Header, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_S4P_Header, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_S4P_Header, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_S4I_Icon = lv_img_create(ui_S4P_Header);
    lv_img_set_src(ui_S4I_Icon, &ui_img_gears_white_png);
    lv_obj_set_width(ui_S4I_Icon, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_S4I_Icon, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_S4I_Icon, -136);
    lv_obj_set_y(ui_S4I_Icon, 10);
    lv_obj_set_align(ui_S4I_Icon, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_S4I_Icon, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_S4I_Icon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_S4I_Icon, 192);

    ui_S4L_Header = lv_label_create(ui_S4P_Header);
    lv_obj_set_width(ui_S4L_Header, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_S4L_Header, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_S4L_Header, 25);
    lv_obj_set_y(ui_S4L_Header, 11);
    lv_obj_set_align(ui_S4L_Header, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_S4L_Header, "Access Point aktiviert");
    lv_obj_set_style_text_font(ui_S4L_Header, &ui_font_Raleway18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_S4SP_Spinner = lv_spinner_create(ui_Screen_WiFi, 1000, 90);
    lv_obj_set_width(ui_S4SP_Spinner, 40);
    lv_obj_set_height(ui_S4SP_Spinner, 40);
    lv_obj_set_x(ui_S4SP_Spinner, 130);
    lv_obj_set_y(ui_S4SP_Spinner, 90);
    lv_obj_set_align(ui_S4SP_Spinner, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_S4SP_Spinner, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_obj_set_style_arc_width(ui_S4SP_Spinner, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_S4SP_Spinner, lv_color_hex(0x00A39B), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_S4SP_Spinner, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_S4SP_Spinner, 5, LV_PART_INDICATOR | LV_STATE_DEFAULT);

}
void ui_Screen_Upload_screen_init(void)
{
    ui_Screen_Upload = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen_Upload, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_S5P_Border = lv_obj_create(ui_Screen_Upload);
    lv_obj_set_width(ui_S5P_Border, 310);
    lv_obj_set_height(ui_S5P_Border, 200);
    lv_obj_set_x(ui_S5P_Border, 1);
    lv_obj_set_y(ui_S5P_Border, 15);
    lv_obj_set_align(ui_S5P_Border, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_S5P_Border, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_S5P_Border, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_S5P_Border, lv_color_hex(0x2B2B2B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_S5P_Border, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_S5P_Border, lv_color_hex(0x00A39B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_S5P_Border, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_S5L_Info_1 = lv_label_create(ui_S5P_Border);
    lv_obj_set_width(ui_S5L_Info_1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_S5L_Info_1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_S5L_Info_1, 0);
    lv_obj_set_y(ui_S5L_Info_1, -2);
    lv_obj_set_align(ui_S5L_Info_1, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_S5L_Info_1, "Zur Zeit sind keine Daten vorhanden.\nBitte oeffnen Sie in Ihrem Browse die IP");
    lv_obj_set_style_text_color(ui_S5L_Info_1, lv_color_hex(0x00A39B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_S5L_Info_1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_S5L_Info_1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_S5L_Info_1, &ui_font_Raleway16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_S4L_Info4 = lv_label_create(ui_S5P_Border);
    lv_obj_set_width(ui_S4L_Info4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_S4L_Info4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_S4L_Info4, 0);
    lv_obj_set_y(ui_S4L_Info4, 65);
    lv_obj_set_align(ui_S4L_Info4, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_S4L_Info4,
                      "und laden die beiden Datein co2.csv\nund costs.csv hoch. Die Dateien benoetigen\nmehrere Datensaetze im folgen Format\nmit einem aktuellen Zeitstempel:\n\n26.03.2023 14:25:15;0,12345");
    lv_obj_set_style_text_color(ui_S4L_Info4, lv_color_hex(0x00A39B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_S4L_Info4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_S4L_Info4, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_S4L_Info4, &ui_font_Raleway16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_S5L_IP = lv_label_create(ui_S5P_Border);
    lv_obj_set_width(ui_S5L_IP, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_S5L_IP, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_S5L_IP, 0);
    lv_obj_set_y(ui_S5L_IP, -40);
    lv_obj_set_align(ui_S5L_IP, LV_ALIGN_CENTER);
    lv_label_set_text(ui_S5L_IP, "192.168.0.1");
    lv_obj_set_style_text_color(ui_S5L_IP, lv_color_hex(0x00A39B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_S5L_IP, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_S5L_IP, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_S5L_IP, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_S5L_IP, &ui_font_Raleway24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_S5P_Header = lv_obj_create(ui_Screen_Upload);
    lv_obj_set_width(ui_S5P_Header, 310);
    lv_obj_set_height(ui_S5P_Header, 50);
    lv_obj_set_x(ui_S5P_Header, 0);
    lv_obj_set_y(ui_S5P_Header, -115);
    lv_obj_set_align(ui_S5P_Header, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_S5P_Header, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_S5P_Header, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_S5P_Header, lv_color_hex(0x202020), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_S5P_Header, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_S5P_Header, lv_color_hex(0x00A39B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_S5P_Header, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_S5P_Header, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_S5P_Header, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_S5P_Header, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_S5I_Icon = lv_img_create(ui_S5P_Header);
    lv_img_set_src(ui_S5I_Icon, &ui_img_gears_white_png);
    lv_obj_set_width(ui_S5I_Icon, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_S5I_Icon, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_S5I_Icon, -136);
    lv_obj_set_y(ui_S5I_Icon, 10);
    lv_obj_set_align(ui_S5I_Icon, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_S5I_Icon, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_S5I_Icon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_S5I_Icon, 192);

    ui_S5L_Header = lv_label_create(ui_S5P_Header);
    lv_obj_set_width(ui_S5L_Header, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_S5L_Header, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_S5L_Header, 30);
    lv_obj_set_y(ui_S5L_Header, 11);
    lv_obj_set_align(ui_S5L_Header, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_S5L_Header, "Datei Upload");
    lv_obj_set_style_text_font(ui_S5L_Header, &ui_font_Raleway18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_S5SP_Spinner = lv_spinner_create(ui_Screen_Upload, 1000, 90);
    lv_obj_set_width(ui_S5SP_Spinner, 40);
    lv_obj_set_height(ui_S5SP_Spinner, 40);
    lv_obj_set_x(ui_S5SP_Spinner, 130);
    lv_obj_set_y(ui_S5SP_Spinner, 90);
    lv_obj_set_align(ui_S5SP_Spinner, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_S5SP_Spinner, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_obj_set_style_arc_width(ui_S5SP_Spinner, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_S5SP_Spinner, lv_color_hex(0x00A39B), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_S5SP_Spinner, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_S5SP_Spinner, 5, LV_PART_INDICATOR | LV_STATE_DEFAULT);

}

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               true, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_Screen_Loading_screen_init();
    ui_Screen_Data_screen_init();
    ui_Screen_Settings_screen_init();
    ui_Screen_WiFi_screen_init();
    ui_Screen_Upload_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_Screen_Loading);
}
